flaskblog/posts/models.py
from datetime import datetime
from flaskblog import db

class Post(db.Model):
    __tablename__ = 'post'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    
    def __init__(self, title, content, user_id):
        super().__init__()
        self.title = title
        self.content = content
        self.user_id = user_id
    
    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms import StringField, SubmitField, TextAreaField

class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField()

    def __init__(self, submit_label="Post", *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.submit.label.text = submit_label
        

flaskblog/main/routes.py
from flask import Blueprint, render_template, request

from flaskblog.posts.models import Post

main = Blueprint("main", __name__)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get("page", 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template("home.html", title="Home", posts=posts)

@main.route("/about")
def about():
    return render_template("about.html", title="About")

flaskblog/users/routes.py
from flaskblog import bcrypt
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flaskblog import db
from flask_login import current_user, login_required, login_user, logout_user

from flaskblog.posts.models import Post
from flaskblog.users.models import User
from flaskblog.users.forms import LoginForm, RegistrationForm, RequestResetForm, ResetPasswordForm, UpdateAccountForm
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint("users", __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(form.username.data, form.email.data, hashed_password)

        db.session.add(user)
        db.session.commit()

        flash(f"Welcome {user.username}! Your account has been created! You are now able to log in", "success")
        return redirect(url_for("users.login"))

    return render_template("register.html", title="Register", form=form)

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Login Unsuccessful. Please check email and password", "warning")

    return render_template("login.html", title="Login", form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))

@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
            
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for("static", filename=f"profile_pics/{current_user.image_file}")
    return render_template("account.html", title="Account", 
                           image_file=image_file, form=form)
    
@users.route("/user/<string:username>")
def user_posts(username: str):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()

    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template("user_posts.html", title=f"Posts by {username}", posts=posts, user=user)

@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent with instructions to reset your password croski.", "info")
        return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="Reset Password", form=form)

@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user: User = User.verify_reset_token(token)
    if not user:
        flash("Invalid or expired token", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()

        flash("Password has been updated!", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_token.html", title="Reset Password", form=form)

#
# @users.route("/bulk_create", methods=["GET", "POST"])
# def bulk_create_users():
#
#     hashed_pass = bcrypt.generate_password_hash("testing").decode('utf-8')
#     u1 = User("BabyTron", "babytronshtyboyz@gmail.com", hashed_pass)
#     u2 = User("John Doe", "johndoe@gmail.com", hashed_pass)
#     u3 = User("Jane Doe", "janedoe@gmail.com", hashed_pass)
#     u4 = User("Taro Yamada", "yamadataro@gmail.com", hashed_pass)
#
#     db.session.add(u1)
#     db.session.add(u2)
#     db.session.add(u3)
#     db.session.add(u4)
#
#     db.session.commit()
#
#     flash("Test users created", "success")
#     return redirect(url_for("main.home"))

flaskblog/templates/about.html
{% extends "layout.html" %}
{% set active_page = "About" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% set active_page = "Account" %}
{% block content %}
<div class="content-section">
    <div class="d-flex">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <br><span class="text-danger">{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info mt-2") }}
        </div>
    </form>
</div>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% set active_page = legend if legend else "" %}
{% block content %}
<div class="content-section">
	<form action="" method="POST">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">{{ legend }}</legend>
			<div class="form-group">
				{{ form.title.label(class="form-control-label") }} 
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
			</div>
			<div class="form-group">
				{{ form.content.label(class="form-control-label") }} 
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
			</div>
		</fieldset>
		<div class="form-group mt-2">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
	</form>
</div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% set active_page = "Home" %}
{% block content %}

{% macro render_pagination() %}
	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
		{% if page_num %}
			{% set page_btn_class = "btn mb-4 " + ("btn-info" if posts.page == page_num else "btn-outline-info") %}
			<a class="{{ page_btn_class }}" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
		{% else %}
			...
		{% endif %}
	{% endfor %}
{% endmacro %}

{{ render_pagination() }}

{% for post in posts.items %}
<article class="d-flex content-section">
	<img class="rounded-circle article-img" src="{{url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="">
	<div class="media-body">
		<div class="article-metadata">
			<a style="font-size: larger;" class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
			<small class="text-muted">{{ post.date_posted.strftime('%B %d, %Y') }}</small>
		</div>
		<h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
		<p class="article-content">{{ post.content }}</p>
	</div>
</article>
{% endfor %}

{{ render_pagination() }}

{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% set page_title = "Flask Blog" + (" - " + title if title else "") %}
    <title>{{ page_title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          {% set nav_bar_left = [
            {"href": "main.home", "title": "Home"},
            {"href": "main.about", "title": "About"}
          ] %}
          {% set nav_bar_auth = [
              {"href": "posts.new_post", "title": "New Post"},
              {"href": "users.account", "title": "Account"},
              {"href": "users.logout", "title": "Logout"}
          ] %}
          {% set nav_bar_unauth = [
              {"href": "users.login", "title": "Login"},
              {"href": "users.register", "title": "Register"}
          ] %}
          {% set active_page = active_page | default("") %}
          <div class="collapse navbar-collapse">
            <li class="navbar-nav mr-auto">
              {% for page in nav_bar_left %}
                {% set nav_class = "nav-item nav-link" + (" active" if page.title == active_page else "") %}
                <a class="{{ nav_class }}" href="{{ url_for(page.href)}}">{{ page.title }}</a>
              {% endfor %}
            </li>
          </div>
          <div class="collapse navbar-collapse" style="display: flex; justify-content: right;">
            <li class="navbar-nav">
              {% set nav_bar_right = nav_bar_auth if current_user.is_authenticated else nav_bar_unauth %}
              {% for page in nav_bar_right %}
                {% set nav_class = "nav-item nav-link" + (" active" if page.title == active_page else "") %}
                <a class="{{ nav_class }}" href="{{ url_for(page.href)}}">{{ page.title }}</a>
              {% endfor %}
            </li>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{category}}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}
          {% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %} 
{% set active_page = "Login" %}
{% block content %}
<div class="content-section">
	<form action="" method="POST">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Log In</legend>
			<div class="form-group">
				{{ form.email.label(class="form-control-label") }} 
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
			</div>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }} 
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
			</div>
			<div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
			</div>
		</fieldset>
		<div class="form-group mt-2">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot password?</a>
            </small>
        </div>
	</form>
</div>
<div class="border-top pt-3">
	<small class="text-muted">
		Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
	</small>
</div>
{% endblock content %}

flaskblog/templates/pagination.html
{% macro render_pagination() %}
    {% set endpoint = kwargs.get("endpoint") %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            {% set page_btn_class = "btn mb-4 " + ("btn-info" if posts.page == page_num else "btn-outline-info") %}
            <a class="{{ page_btn_class }}" href="{{ url_for(endpoint, page=page_num) }}">{{ page_num }}</a>
        {% else %}
            <span>...</span>
        {% endif %}
    {% endfor %}
{% endmacro %}

flaskblog/templates/post.html
{% extends "layout.html" %} {% set active_page = "Post" %} {% block content %}
<article class="d-flex content-section">
	<img
		class="rounded-circle article-img"
		src="{{url_for('static', filename='profile_pics/' + post.author.image_file) }}"
		alt=""
	/>
	<div class="media-body">
		<div class="article-metadata">
			<a
				style="font-size: larger"
				class="mr-2"
				href="{{ url_for('users.user_posts', username=post.author.username) }}"
				>{{ post.author.username }}
			</a>
			<small class="text-muted">{{ post.date_posted.strftime('%B %d, %Y') }}</small>
			<br />
			{% if post.author == current_user %}
			<a
				class="btn btn-secondary btn-sm mt-1 mb-1"
				href="{{ url_for('posts.update_post', post_id=post.id) }}"
			>
				Update
			</a>
			<button
				type="button"
				class="btn btn-danger btn-sm m-1"
				data-bs-toggle="modal"
				data-bs-target="#deleteModal"
			>
				Delete
			</button>
			{% endif %}
		</div>
		<h2 class="article-title">{{ post.title }}</h2>
		<p class="article-content">{{ post.content }}</p>
	</div>
</article>
<!-- Modal -->
<div
	class="modal fade"
	id="deleteModal"
	tabindex="-1"
	aria-labelledby="deleteModalLabel"
	aria-hidden="true"
>
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title fs-5" id="deleteModalLabel">Delete Post?</h1>
				<button
					type="button"
					class="btn-close"
					data-bs-dismiss="modal"
					aria-label="Close"
				></button>
			</div>
			<div class="modal-body">This action cannot be undone.</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
					Close
				</button>
				<form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
					<input class="btn btn-danger" type="submit" value="Delete" />
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

flaskblog/templates/register.html
{% extends "layout.html" %} 
{% set active_page = "Register" %}
{% block content %}
<div class="content-section">
	<form action="" method="POST">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Join Today</legend>
			<div class="form-group">
				{{ form.username.label(class="form-control-label") }} 
                {% set username_class = "form-control form-control-lg" + (" is-invalid" if form.username.errors else "") %}
                {{ form.username(class=username_class) }}
                {% if form.username.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% endif %}
			</div>
			<div class="form-group">
				{{ form.email.label(class="form-control-label") }} 
                {% set email_class = "form-control form-control-lg" + (" is-invalid" if form.email.errors else "") %}
                {{ form.email(class=email_class) }}
                {% if form.email.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% endif %}
			</div>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }} 
                {% set password_class = "form-control form-control-lg" + (" is-invalid" if form.password.errors else "") %}
                {{ form.password(class=password_class) }}
                {% if form.password.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% endif %}
			</div>
			<div class="form-group">
				{{ form.confirm_password.label(class="form-control-label") }} 
                {% set confirm_password_class = "form-control form-control-lg" + (" is-invalid" if form.confirm_password.errors else "") %}
                {{ form.confirm_password(class=confirm_password_class) }}
                {% if form.confirm_password.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% endif %}
			</div>
		</fieldset>
		<div class="form-group mt-2">{{ form.submit(class="btn btn-outline-info") }}</div>
	</form>
</div>
<div class="border-top pt-3">
	<small class="text-muted">
		Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
	</small>
</div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% set active_page = "Reset Request" %}
{% block content %}
<div class="content-section">
	<form action="" method="POST">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">{{ active_page }}</legend>
			<div class="form-group">
				{{ form.email.label(class="form-control-label") }} {% if form.email.errors %} {{
				form.email(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.email.errors %}
					<span>{{error}}</span>
					{% endfor %}
				</div>
				{% else %} {{ form.email(class="form-control form-control-lg") }} {% endif %}
			</div>
		</fieldset>
		<div class="form-group mt-2">{{ form.submit(class="btn btn-outline-info") }}</div>
	</form>
</div>
{% endblock content %}

flaskblog/templates/reset_token.html
{% extends "layout.html" %}
{% set active_page = "Reset Password" %}
{% block content %}
<div class="content-section">
	<form action="" method="POST">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">{{ active_page }}</legend>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }} {% if form.password.errors %} {{
				form.password(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.password.errors %}
					<span>{{error}}</span>
					{% endfor %}
				</div>
				{% else %} {{ form.password(class="form-control form-control-lg") }} {% endif %}
			</div>
            <div class="form-group">
				{{ form.confirm_password.label(class="form-control-label") }} {% if form.confirm_password.errors %} {{
				form.confirm_password(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.confirm_password.errors %}
					<span>{{error}}</span>
					{% endfor %}
				</div>
				{% else %} {{ form.confirm_password(class="form-control form-control-lg") }} {% endif %}
			</div>
		</fieldset>
		<div class="form-group mt-2">{{ form.submit(class="btn btn-outline-info") }}</div>
	</form>
</div>
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% set active_page = "User Posts" %}
{% block content %} 

{% macro render_pagination() %}
	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
		{% if page_num %}
			{% set page_btn_class = "btn mb-4 " + ("btn-info" if posts.page == page_num else "btn-outline-info") %}
			<a class="{{ page_btn_class }}" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
		{% else %}
            <span>...</span>
		{% endif %}
	{% endfor %}
{% endmacro %}

<h1 class="mb-3">Posts by {{ user.username }} ({{posts.total}}) </h1>

{{ render_pagination() }}

{% for post in posts.items %}
<article class="d-flex content-section">
	<img class="rounded-circle article-img" src="{{url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="">
	<div class="media-body">
		<div class="article-metadata">
			<a style="font-size: larger;" class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
			<small class="text-muted">{{ post.date_posted.strftime('%B %d, %Y') }}</small>
		</div>
		<h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
		<p class="article-content">{{ post.content }}</p>
	</div>
</article>
{% endfor %}

{{ render_pagination() }}

{% endblock content %}